pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                echo 'building the application...'
                git branch: 'main', url: 'https://github.com/kma-project-hakdong/web-Ecumerce/'
            }
        }
        stage('test') {
            steps {
                echo 'testing the application...'
            }
        }
        stage('deploy') {
            steps {
                echo 'deploying the application...'
                echo pwd
                script {
                    sh '''
                        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${ECR_REGISTRY}
                    '''
                }
            }
        }
    }
}