pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                echo 'building the application...'
                git branch: 'main', url: 'https://github.com/kma-project-hakdong/web-Ecumerce/'
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
            }
        }
        stage('test') {
            steps {
                echo 'testing the application...'
            }
        }
        stage('Docker build and Push') {
            steps {
                echo 'deploying the application...'
            }
        }
    }
}