pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out the application...'
                git branch: 'main', url: 'https://github.com/kma-project-hakdong/web-Ecumerce/'
            }
        }

        stage('Docker Build and Push') {
            steps {
                echo 'Building and deploying the application...'
                script {
                    docker.withRegistry('https://851725431361.dkr.ecr.ap-northeast-2.amazonaws.com', 'ecr-admin') {

                        def myapp = docker.build("851725431361.dkr.ecr.ap-northeast-2.amazonaws.com/kma-web:${env.BUILD_ID}")
                        myapp.push()
                        myapp.push('latest')
                    }
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Testing the application...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying the application...'
            }
        }
    }
}
